seed: 1
model: 'tcspace'
exp_name: riverraid
resume: false
load_time_consistency: true
add_flow: true
resume_ckpt: ''
parallel: true
device_ids: [0, 1, 2, 3]
device: 'cuda:0'

logdir: '../output/logs/final'
checkpointdir: '../output/checkpoints/final'
evaldir: '../output/eval/final'

dataset: 'ATARI'
dataset_style: '_128'
dataset_roots:
  OBJ3D_SMALL: '../data/OBJ3D_SMALL'
  OBJ3D_LARGE: '../data/OBJ3D_LARGE'
  ATARI: '../aiml_atari_data_final/space_like'


train:
  log: true
  batch_size: 16
  max_epochs: 10000
  max_steps: 5000
  print_every: 200
  save_every: 500
  num_workers: 4
  clip_norm: 1.0
  max_ckpt: 4
  eval_on: true
  eval_every: 200
  solver:
    fg:
      optim: 'RMSprop'
      lr: 3e-5
    bg:
      optim: 'Adam'
      lr: 1e-3

arch:
  motion_input: false
  motion: true
  motion_kind: 'mode'
  G: 16
  fg_sigma: 0.20

  z_pres_start_step: 0
  z_pres_end_step: 5000
  z_pres_start_value: 0.1
  z_pres_end_value: 1e-10

  z_scale_mean_start_step: 0
  z_scale_mean_end_step: 5000
  z_scale_mean_start_value: -2.0
  z_scale_mean_end_value: -2.5

  tau_start_step: 0
  tau_end_step: 10000
  tau_start_value: 2.5
  tau_end_value: 2.5

  fix_alpha_steps: -1
  fix_alpha_value: 0.1

  motion_underestimating: 1.5
  motion_object_found_lambda: 0.025
  z_where_offset: 0.2

  K: 4
  bg_sigma: 0.10

gamelist: [
    'Riverraid-v0',
    ]

